name: CI/CD for LEMP Containers

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/lemp-backend:latest
            ${{ env.DOCKERHUB_USERNAME }}/lemp-backend:${{ github.sha }}
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/lemp-frontend:latest
            ${{ env.DOCKERHUB_USERNAME }}/lemp-frontend:${{ github.sha }}

  copy-init-sql:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout (for db/init/init.sql)
        uses: actions/checkout@v4
      - name: Ensure target dir exists on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /opt/lemp/db/init
            sudo chown $USER:$USER /opt/lemp/db/init
      - name: Copy init.sql to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "db/init/init.sql"
          target: "/opt/lemp/db/init/"
          strip_components: 2

  deploy:
    runs-on: ubuntu-latest
    needs: copy-init-sql
    steps:
      - name: Compose pull & restart on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /opt/lemp
            docker compose pull
            docker compose up -d
            docker compose ps
